### ISSUE TITLE
[BUG]关于AdaptivePool

### ISSUE THREAD

**Issue by Asthestarsfalll** [MegEngine/invis#1]
发现了关于AdaptivePool的几个小bug：
1. AdaptivePool1d似乎只支持`output_shape`为1，可能因为[此处](https://github.com/MegEngine/invis/blob/main/invis/tensor/function/redef_func.py#L465-L473)使用expand_dims转换为4-d，最后一个维度为1.
2. 可能无法使用import invis as torch的方式调用`AdaptiveAvgPool2d(oshp)`，因为其与torch的参数名称不同`AdaptiveAvgPool2d(output_size)`
3. 某些情况下，当output_size不为1时，AdaptivePool的输出不能与torch对齐，因为megengine中kernel与stride推断与torch中不相同，见[此](https://www.megengine.org.cn/doc/stable/zh/reference/api/megengine.module.AdaptiveAvgPool2d.html?highlight=adaptive#megengine.module.AdaptiveAvgPool2d)和[此]( https://github.com/pytorch/pytorch/blob/877c96cddfebee00385307f9e1b1f3b4ec72bfdc/aten/src/ATen/native/AdaptiveAveragePooling.cpp#L12-L72)  ，  而很多网络会使用不同output_size大小的AdaptivePool，这方面会有支持的打算吗？

**Comment by FateScript** [comment]
@Asthestarsfalll 感谢反馈，我先看一下哈（invis是一个experimental的东西，如果有兴趣的话可以协助做contribute）
